version: '3.1'

services:

  fastapi-taskman-db:
    image: postgres:12.5
    environment:
      POSTGRES_USER: fastapi_taskman
      POSTGRES_PASSWORD: fastapi_taskman
      POSTGRES_DB: fastapi_taskman
    ports:
      - "5432:5432"

    networks:
      - fastapi-taskman-network

networks:
  fastapi-taskman-network:
    driver: bridge
