version: '3.1'

services:

  fastapi-taskman-db:
    image: postgres:12.5
    env_file:
      - ./.env
    ports:
      - "5432:5432"

    networks:
      - fastapi-taskman-network

networks:
  fastapi-taskman-network:
    driver: bridge
